[default_apps]
# teams = "teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --url {meeting_url}"
# calendar_client = "thunderbird"
terminal = "kitty"
files = "dolphin"

[debug]
try_suppress_errors     =   false                                   
try_suppress_warnings   =   true                                    
app_paths               =   ["~/.local/share/applications/"]        

[units]
lengths                 =   "meter"
weights                 =   "kg"
volumes                 =   "l"
temperatures            =   "C"

[appearance]
width                   =   900                                       
height                  =   593                                       
gsk_renderer            =   "cairo"                                   
recolor_icons           =   false                                     
icon_paths              =   [ "~/.local/share/icons/"]             
icon_size               =   22                                        
search_icon             =   false                                     
use_base_css            =   true
status_bar              =   false

[behavior]
caching                 =   true                                    
cache                   =   "~/.cache/sherlock_desktop_cache.json"  
daemonize               =   false                                   
animation               =   true                                    
global_prefix           =   ""                                   
global_flags            =   ""                                    

[binds]
prev                    =   "None"                                  
next                    =   "None"                                  
modifier                =   "control"                               

[files]
fallback                =   "~/.config/sherlock/fallback.json"
css                     =   "~/.config/sherlock/style.css"
alias                   =   "~/.config/sherlock/sherlock_alias.json"
ignore                  =   "~/.config/sherlock/sherlockignore"
