-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AU Optronics 0x7AA7",
  mode = "2560x1600@90.00",
  position = "0x0",
  scale = 1.25,
  vrr = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
