format = """
[](#8A7F6D)\
$os\
$username\
[](bg:#659431 fg:#8A7F6D)\
$directory\
[](fg:#659431 bg:#469754)\
$git_branch\
$git_status\
[](fg:#469754 bg:#629D5A)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#629D5A bg:#A7BD4E)\
$docker_context\
[](fg:#A7BD4E bg:#94A662)\
$time\
[ ](fg:#94A662)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#8A7F6D"
style_root = "bg:#8A7F6D"
format = '[$user ](fg:#FFFFFF $style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#8A7F6D"
disabled = true # Disabled by default

[directory]
style = "bg:#659431"
format = "[ $path ](fg:#FFFFFF $style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[docker_context]
symbol = " "
style = "bg:#A7BD4E"
format = '[ $symbol $context ](fg:#FFFFFF $style)'

[elixir]
symbol = " "
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg: #FFFFFF$style)'

[elm]
symbol = " "
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[git_branch]
symbol = ""
style = "bg:#469754"
format = '[ $symbol $branch ](fg:#FFFFFF $style)'

[git_status]
style = "bg:#469754"
format = '[$all_status$ahead_behind ](fg:#FFFFFF $style)'

[golang]
symbol = " "
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[gradle]
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[haskell]
symbol = " "
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[java]
symbol = " "
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[julia]
symbol = " "
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[nodejs]
symbol = ""
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[nim]
symbol = "󰆥 "
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[rust]
symbol = ""
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[scala]
symbol = " "
style = "bg:#629D5A"
format = '[ $symbol ($version) ](fg:#FFFFFF $style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#94A662"
format = '[ 󰋑 $time ](fg:#FFFFFF $style)'
